import type { Metadata } from 'next';
import { Container, CssBaseline } from '@mui/material';
import ButtonAppBar from './components/ButtonAppBar';
import Provider from './components/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <CssBaseline />
      <html lang="en">
        <body>
          <ButtonAppBar />
          <Container>{children}</Container>
        </body>
      </html>
    </Provider>
  );
}
